### ISSUE TITLE
timeline on * index pattern

### ISSUE THREAD

**Issue by bertol83** [sirensolutions/kibi_timeline_vis#109]
1. Create an index pattern *
2. Create a saved search on index pattern *
3. Create a timeline visualization
4. Select one of the date fields available
5. Run the visualization (green button)

![image](https://cloud.githubusercontent.com/assets/13969336/22106578/40d92266-de41-11e6-912e-bb5cd0836b8e.png)

**Comment by giorgio94c** [comment]
Is this for _sprint-5_, @szydan ?

**Comment by szydan** [comment]
@giorgio94c  Looks like a nasty bug so please try to reproduce/investigate

**Comment by bertol83** [comment]
now yes, we need it

**Comment by giorgio94c** [comment]
@fabiocorneti you estimate this issue 8: maybe you have a hint for me about how solve this?

**Comment by fabiocorneti** [comment]
I think I set that by mistake, should take less than 8 days; set the correct estimate once you investigate the issue.

**Comment by SergeyBondarenko** [comment]
@giorgio94c, the error message says that the object `hit` doesn't have the property `fields`. There is the code that uses the property but somehow it is not defined in this case. Start debugging from the following lines:
```
[trex@Latitude-E5510 kibi_timeline_vis]$ grep -rn "hit.fields" ../kibi_timeline_vis/
../kibi_timeline_vis/public/kibi_timeline.js:207:              startRawFieldValue = hit.fields[params.startField];
../kibi_timeline_vis/public/kibi_timeline.js:219:                endRawFieldValue = hit.fields[params.endField];
```

**Comment by giorgio94c** [comment]
Thanks @SergeyBondarenko but I already seen that when I took the issue ;)
