### ISSUE TITLE
add issue/PR templates

### ISSUE THREAD

**Issue by scampi** [sirensolutions/kibi_timeline_vis#120]
see https://github.com/sirensolutions/kibi/tree/master/.github

**Comment by giorgio94c** [comment]
It's just about add this file, right?

**Comment by scampi** [comment]
yes, and another one similar but that is used when a PR is created.

**Comment by giorgio94c** [comment]
@scampi so what I did in PR is not enough?

**Comment by scampi** [comment]
https://github.com/blog/2111-issue-and-pull-request-templates
