### ISSUE TITLE
update to 6.0.0

### ISSUE THREAD

**Issue by theredfoxlee** [sirensolutions/kibi_timeline_vis#153]
Is kibi_timeline_vis going to be updated to Kibana **6.0.0**? If so, **when**?

**Comment by jccq** [comment]
hi theredfoxlee it will be past February for us to do this, we're pretty taken with the new Siren 10 release https://siren.io/siren-543-released-and-version-10-is-coming/ , feel free to contribute earlier if you'd like shouldnt be too difficult.
