### ISSUE TITLE
Content is empty when looking in dashboard mode

### ISSUE THREAD

**Issue by PDCLeska** [sirensolutions/kibi_timeline_vis#17]
While events are shown when looking at the timeline in visualizing mode, it becomes empty when turning to dashboard mode. any idea why?

**Comment by jccq** [comment]
please look at the demo we ship (the one that comes with Kibi,
articles/companies/investmnets/investors) In the "companies" tab you can
select the "timeline" dashboard from the dropdown menu of the "tab"  in
there you will see the visualization works.
how does your data/configuration differ from that in that dashboard?
that can help us answer :)



On Mon, May 2, 2016 at 3:30 PM, PDCLeska <notifications@github.com> wrote:

> While events are shown when looking at the timeline in visualizing mode,
> it becomes empty when turning to dashboard mode. any idea why?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sirensolutions/kibi_timeline_vis/issues/17>
>



-- 
Giovanni Tummarello
CEO - SIREn Solutions

**Comment by PDCLeska** [comment]
Im using the plugin on Kibana 4.5. Not sure where you are pointing me to look for. Should I download kibi? Note That When clicking the pen icon to edit the visualization, the component opens up and event are populated. It is only after I save and go back to the dashboard tab that the time line is empty.

**Comment by jccq** [comment]
Ah ok

we are not currently supporting Kibana 4.5 yet.
If its an urgency we can provide priority support as part of our services.
Alternatively, we'll notify once the compatibility is updated.
Thanks


On Mon, May 2, 2016 at 4:10 PM, PDCLeska <notifications@github.com> wrote:

> Im using the plugin on Kibana 4.5. Not sure where you are pointing me to
> look for. Should I download kibi? Note That When clicking the pen icon to
> edit the visualization, the component opens up and event are populated. It
> is only after I save and go back to the dashboard tab that the time line is
> empty.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/sirensolutions/kibi_timeline_vis/issues/17#issuecomment-216262722>
>



-- 
Giovanni Tummarello
CEO - SIREn Solutions

**Comment by PDCLeska** [comment]
Thanks!

**Comment by scampi** [comment]
@PDCLeska Please have a look at the new release https://github.com/sirensolutions/kibi_timeline_vis/releases/tag/0.1.4

**Comment by PDCLeska** [comment]
Thanks! will test it on .5 when back in office.

Regards,
Amir
