### ISSUE TITLE
Unable to install 0.1.4 on kibana 4.4.1

### ISSUE THREAD

**Issue by nreese** [sirensolutions/kibi_timeline_vis#24]
I am attempting to install the timeline visualization plugin onto a kibana without internet access. I brought in the zip downloaded from https://github.com/sirensolutions/kibi_timeline_vis/archive/0.1.4.zip. 

When running the command `kibana plugin -i kibi_timeline_vis -u http://host/kibi_timeline_vis-0.1.4.zip`, kibana returns the following errors...

`Module build failed: ModuleNotFoundError: Module not found: Error: Cannot resolve module 'kibi-icons/lib/stylesheets/FontAwesomeKibi.css' in /data/kibana/kibana-4.4.1-linux-x64/installedPlugins/kibi_timeline_vis/public `

Can the kibi timeline visualization be installed into a standalone kibana instance? Does the plugin installation attempt to download any dependencies not included in the zip file?

Thanks,
Nathan

**Comment by jccq** [comment]
Hi Nathan in theory yes it should be possible to use it in Kibana, in practice please bear with us as we wouldnt have time at the moment to maintain this plugin tested for Kibana. 
We do test it  and ship it with Kibi, have you tried in there? 
if it works in there is there any particular reason why you cant use kibi? (its useful for us to know.. we try to make sure kibi doesnt detract anything from kibana). 

At the same time if you have a pull request to fix this issue for others please feel free to submit and we'll integrate it, thanks in advance.

**Comment by scampi** [comment]
you should try the 0.1.4 from https://github.com/sirensolutions/kibi_timeline_vis/tree/master/target as it contains all the dependencies, while the archive do not.

**Comment by nreese** [comment]
That zip worked. The github released zips do not contain the required
dependencies. Thanks for pointing this out

**Comment by scampi** [comment]
cool! I updated the release page https://github.com/sirensolutions/kibi_timeline_vis/releases with the zip balls
