### ISSUE TITLE
ES query should retrieve the last X (limit) documents

### ISSUE THREAD

**Issue by grdut** [sirensolutions/kibi_timeline_vis#33]
Hi,

In my opinion the ES query generated by your plugin should retrieve the **last** X (limit - default 100) documents matching the criteria and not the **first** X documents as it's the case actually because in my opinion the current view could easily be misleading while using the timeline to track/display the latest events.

Or even better, we could have an option in the "Option" tab to select if we want our limit to be ascending or descending. 

Thanks.

**Comment by szydan** [comment]
@grdut  in this PR 
https://github.com/sirensolutions/kibi_timeline_vis/pull/118
an option was added to order the results from ES which we hope should address this ticket
