### ISSUE TITLE
When I start kibana with the latest 

### ISSUE THREAD

**Issue by digitalrinaldo** [sirensolutions/kibi_timeline_vis#40]
Did the following

gulp package
unzip target/kibi_timeline_vis-4.5.3.zip  -d /opt/kibana/installedPlugins/

I restart kibana and kibana never comes back online

**Comment by lmangani** [comment]
Hi @digitalrinaldo could please post the Kibana version + logs (or syslog)

**Comment by scampi** [comment]
In addition to @lmangani requests, you can get the visualization at https://github.com/sirensolutions/kibi_timeline_vis/releases/tag/4.5.3 so that you don't have to build it yourself.

**Comment by lmangani** [comment]
Just validated plugin installation without issues on latest Kibana 4.5.4 using release package:
```
./bin/kibana plugin -i kibi_timeline_vis -u https://github.com/sirensolutions/kibi_timeline_vis/raw/4.5.3/target/kibi_timeline_vis-4.5.3.zip
```

**Comment by digitalrinaldo** [comment]
The package I built must have had issues.  Thanks for the great work on this plugin.
