### ISSUE TITLE
timeline not using kibana time zone configuration 

### ISSUE THREAD

**Issue by nreese** [sirensolutions/kibi_timeline_vis#41]
Kibana has a configuration item to set the timezone - `dateFormat:tz`. The kibi-timeline displays times in the machine time zone and not in the time zone provided by kibana. The preferred functionality would be to display the timeline in the time zone provided by kibana and not the time zone provided by the machine

**Comment by scampi** [comment]
@nreese Can you provide some sample data where I could see this in action ?
That would help a lot!

**Comment by nreese** [comment]
Below are instructions to reproduce the problem.
1. modify the kibana time zone configuration to a time zone other than the
machine time zone under settings->advanced->dataFormat:tz. Set to something
like UTC
2. set the absolute time to a calendar day such as 2016-08-25T00:00:00 to
2016-08-26T00:00:00
3. Create a timeline visualization. Notice how the time axis does not line
up with UTC time. I am located in Denver, Colorado which is -6:00 from UTC.
The time axis runs from 2016-08-24T18:00:00 to 2016-08-25T18:00:00 instead
of the expected 2016-08-25T00:00:00 to 2016-08-26T00:00:00

On Thu, Aug 25, 2016 at 9:11 AM, Stéphane Campinas <notifications@github.com
