### ISSUE TITLE
write tests

### ISSUE THREAD

**Issue by scampi** [sirensolutions/kibi_timeline_vis#44]

**Comment by giorgio94c** [comment]
Can I have some informations about what did you expect from this issue? :)

**Comment by szydan** [comment]
@giorgio94c as a start can you investigate this one 
https://github.com/sirensolutions/kibi_timeline_vis/issues/34
Fix if there is a fix to make and add a test to make sure it works as expected

**Comment by giorgio94c** [comment]
Ok, sure!
