### ISSUE TITLE
Null fields do not accept by the timeline 

### ISSUE THREAD

**Issue by kayou11** [sirensolutions/kibi_timeline_vis#45]
This error appears when there are null field in starting data : 

Error: hit.fields is undefined
onResults/<@http://localhost:5606/bundles/kibana.bundle.js?v=12273:162398:16
arrayEach@http://localhost:5606/bundles/commons.bundle.js?v=12273:6834:14
createForEach/<@http://localhost:5606/bundles/commons.bundle.js?v=12273:8890:14
onResults@http://localhost:5606/bundles/kibana.bundle.js?v=12273:162395:14
processQueue@http://localhost:5606/bundles/commons.bundle.js?v=12273:42507:29
scheduleProcessQueue/<@http://localhost:5606/bundles/commons.bundle.js?v=12273:42523:28
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:5606/bundles/commons.bundle.js?v=12273:43767:17
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:5606/bundles/commons.bundle.js?v=12273:43585:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:5606/bundles/commons.bundle.js?v=12273:43875:14
done@http://localhost:5606/bundles/commons.bundle.js?v=12273:38304:37
completeRequest@http://localhost:5606/bundles/commons.bundle.js?v=12273:38502:8
requestLoaded@http://localhost:5606/bundles/commons.bundle.js?v=12273:38443:10

**Comment by giorgio94c** [comment]
Just a little thing I've noticed now: I need to "cut the label" of checkbox because we can't see the tooltip :/
