### ISSUE TITLE
Kibana 5.0 support

### ISSUE THREAD

**Issue by pkese** [sirensolutions/kibi_timeline_vis#58]
I'm having issues installing this plugin to Kibana 5.

`bin/kibana-plugin install` says there's no plugin in the .zip archive.

Any ideas?

**Comment by scampi** [comment]
kibana 5 is not supported yet

**Comment by tianchao-haohan** [comment]
+1

**Comment by xycloud** [comment]
+1

**Comment by szydan** [comment]
https://github.com/sirensolutions/kibi_timeline_vis/pull/126 was closed 
There is a pre-release
https://github.com/sirensolutions/kibi_timeline_vis/releases

Official release will follow shortly
