### ISSUE TITLE
support arrays as values of the parameters label/startDate/endDate

### ISSUE THREAD

**Issue by scampi** [sirensolutions/kibi_timeline_vis#60]
The method `TimelineHelper.prototype.getDescendantPropValue` needs to be rewritten to support that

**Comment by tianchao-haohan** [comment]
+1

**Comment by scampi** [comment]
## Multivalued start/end dates

- The `startDate` and `endDate` fields of an event should have the same number of values.
- If this is not the case, then a warning would be displayed.

## Multivalued label field

- Output a comma-separated value in such a case

**Comment by SergeyBondarenko** [comment]
@scampi what do you mean by _support arrays as values of the parameters label/startDate/endDate_?
Now the method mentioned above takes as arguments an object of a found element with all its properties as `obj` variable and the Event label, Event start date and Event end date as `propertyPath`. Then it returns values of the object properties, one by one. What's wrong with that?

**Comment by scampi** [comment]
That method does not exist anymore. In case of an array, we currently take its first element. This issue is about trying to support arrays for the different cases of start/end dates and label fields.
