### ISSUE TITLE
does not react to timepicker update

### ISSUE THREAD

**Issue by scampi** [sirensolutions/kibi_timeline_vis#61]

**Comment by scampi** [comment]
cannot reproduce, I think I got confused by the sync time feature

**Comment by nreese** [comment]
Can this issue be reopened?

I would expect the timeline to fetch new data when Kibana's (or Kibi's) timepicker is set to a new value. I would also expect the timeline to redraw and display the new search results and the new time range. This is not the case.

Steps to reproduce on kibana 4.4.3.
Set the timepicker to an absolute range of a day. Create a timeline visualization that has results for that day. 
Use the timepicker to update the time to different day. Notice that the timeline does not move to the new time range. Notice that new data was not pulled from the server.

**Comment by nreese** [comment]
Looks like this is only an issue while on the visualization pane. When on a dashboard pane, everything works great.

**Comment by scampi** [comment]
thanks for checking

**Comment by scampi** [comment]
@nreese could you try the branch https://github.com/sirensolutions/kibi_timeline_vis/pull/87 on kibana to see if this fixes the problem ? thanks

**Comment by nreese** [comment]
That worked great. Now the timeline reacts to the timepicker in both the visualization tab and the dashboard tab. Thanks
