### ISSUE TITLE
Master is broken - Cannot resolve module 'kibiutils'

### ISSUE THREAD

**Issue by nreese** [sirensolutions/kibi_timeline_vis#70]
Looks like a file has not been committed to master. kibi_timeline.js requires kibiutils which does not exist.

`const kibiUtils = require('kibiutils');`

**Comment by scampi** [comment]
Can you try this branch https://github.com/sirensolutions/kibi_timeline_vis/tree/issue70 ?

**Comment by nreese** [comment]
That fixed the build issue but their is another issue.  The plugin no longer grabs the event label.

![image](https://cloud.githubusercontent.com/assets/373691/20350181/13b2272c-abcb-11e6-9ae4-deb84ffc5527.png)

**Comment by scampi** [comment]
what is the configuration of the vis ? Are you on Kibi or on Kibana ?

**Comment by nreese** [comment]
Kibana 4.6

On Wed, Nov 16, 2016 at 8:26 AM, Stéphane Campinas <notifications@github.com
