### ISSUE TITLE
visualization is not redrawn when the size of the panel changes

### ISSUE THREAD

**Issue by scampi** [sirensolutions/kibi_timeline_vis#79]
![output](https://cloud.githubusercontent.com/assets/795879/20892002/68de8d56-bb04-11e6-93e4-cb5a4b7a4457.gif)

**Comment by giorgio94c** [comment]
Sorry for question but what's the problem [here](https://github.com/sirensolutions/kibi_timeline_vis/blob/master/public/kibi_timeline_vis_controller.js#L36)?
I read this comment:

> // ! does not work correctly inside the panel
> // instead we would have to calculate the proper height on panel resize and change it
> // on change timeline directive should call redraw()

but I have modified the code in this way:
```
width: '100%',
height: '100%',
selectable: true,
autoResize: true
```
and it works :/ Maybe there are other problems in another use cases?

**Comment by szydan** [comment]
@giorgio94c - please test in both cases 
* on the dashboard when you resize the panel by dragging a corner 
* in config mode when you resize the area by opening inspector or changing the window size

**Comment by giorgio94c** [comment]
@szydan 

> on the dashboard when you resize the panel by dragging a corner

Done and it works!

> in config mode when you resize the area by opening inspector...

![screenshot from 2017-01-04 15-09-42](https://cloud.githubusercontent.com/assets/16083521/21644910/1f67dcf6-d290-11e6-8c30-ac448c78a60d.png)

> ...or changing the window size

![screenshot from 2017-01-04 15-09-38](https://cloud.githubusercontent.com/assets/16083521/21644922/31ff1208-d290-11e6-86ef-24dfae2c4a3e.png)

I can create gif if you want ;)

**Comment by scampi** [comment]
and if you open the spy panel ?

**Comment by giorgio94c** [comment]
@scampi no problem: I can open and close spy panel and timeline continue to work...

**Comment by szydan** [comment]
What about refreshing a dashboard with timeline 
Currently, I'm getting this
<img width="1440" alt="screen shot 2017-01-04 at 15 21 18" src="https://cloud.githubusercontent.com/assets/900118/21645539/aae0b63e-d292-11e6-9c52-d69b8ecfe25d.png">

**Comment by giorgio94c** [comment]
@szydan No, nothing similar now...

**Comment by giorgio94c** [comment]
Reopened due to failing tests after new changes.
Apologies!

**Comment by szydan** [comment]
@giorgio94c np I've just added automatic PR builder so it should catch such cases in the future
