### ISSUE TITLE
update timeline lib to 4.17.0

### ISSUE THREAD

**Issue by scampi** [sirensolutions/kibi_timeline_vis#81]

**Comment by tianchao-haohan** [comment]
Is there any release note on this update?

**Comment by scampi** [comment]
https://github.com/almende/vis/releases/tag/v4.17.0
many bug fixes and some new features too

**Comment by tianchao-haohan** [comment]
Is this update released to kibi_timeline_vis-4.5.4.zip?

**Comment by scampi** [comment]
no

**Comment by scampi** [comment]
or maybe
