### ISSUE TITLE
in order to deal with multifield, try to get the docvalues field for retrieving the label

### ISSUE THREAD

**Issue by scampi** [sirensolutions/kibi_timeline_vis#84]
see https://github.com/elastic/kibana/pull/7302 for some example

**Comment by SergeyBondarenko** [comment]
the thing is some values may not be stored
and so, you may need to retrieve from both source and doc_values
(that is, in addition to the problem of multifield)
kibana cannot really tell if a field was in the original doc or was a multifield

Doc:
https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-fields.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/doc-values.html
