### ISSUE TITLE
Saved search select only shows first 100 saved searches.

### ISSUE THREAD

**Issue by nreese** [sirensolutions/kibi_timeline_vis#99]
The select box for picking the saved search id currently just returns the first 100 saved searches. How do you find a search past this initial 100 limit if you have more than 100 saved searches in a kibana instance?

**Comment by scampi** [comment]
I think what you want is proposed in https://github.com/sirensolutions/kibi_timeline_vis/issues/36 ?

**Comment by nreese** [comment]
@scampi This issue is not similar to #36. #36 focuses on limiting the number of events returned from a saved search. This issue is not about the events returned from a saved search. This issue is about how the options for the `Saved Search id ` select element are populated. The current implementation populates the select with the first 100 saved searches. With the current implementation, it is not possible to find any newly created saved searches after the kibana instance contains more than 100 saved searches.

**Comment by scampi** [comment]
ah ok, thanks for the clarification!
